### ISSUE TITLE
I have a small question about developing a TMDB scraper addon.

### ISSUE THREAD

**Issue by teemokin** [i96751414/plugin.video.flix#11]
Is there a way to fetch metadata from TMDBHelper like that?
I want to apply TMDB metadata to a list that only contains titles.
Is searching for a title in the TMDB API, finding its TMDB ID, and then fetching the information again the only method?
So basically, I want to fetch a catalog(movie list) from elsewhere and then apply TMDB metadata to it.

one more thing..
![wow](https://github.com/i96751414/plugin.video.flix/assets/115414852/99bf8857-301d-4bb9-8e20-64560e8e48be)
What part of the script should I refer to in order to learn about the overlay in the top right corner?

**Comment by i96751414** [comment]
Sorry for some reason I did not see this issue. Do you already have the answer for this?

**Comment by teemokin** [comment]
@i96751414 


problem solved
