### ISSUE TITLE
Can't access file system on Apple TV

### ISSUE THREAD

**Issue by BTopbas** [i96751414/plugin.video.flix#3]
On Apple TV file system access is limited. So I jailbreak my Apple TV for better use of Kodi. Now I can access folders and create folders/files. But in the Kodi file system is starting with special://envhome/ i don't know what is this but maybe this is ios apps special file system.

In flix settings, I am able to surf in folders, created a lib folder inside Documents folder. So I selected this folder for Kodi library(special://envhome/Documents/lib).

But when open addon and select item then add to library addon gives "[errno 1] Operation not permitted:'special:'"

So I think addon can't access this folder? 

I created a subtitle folder near lib and select in settings custom subtitle download folder. then try searching subtitle and subtitle downloaded with no problem. I can see subtitle file in subtitle folder. So Kodi access this folders but addon not?

**Comment by BTopbas** [comment]
Solved with:
in library.py 
`import xbmc`
and changed 
`self._directory = get_library_path()`
to 
`self._directory = xbmc.translatePath("special://envhome/Documents/lib")`

**Comment by BTopbas** [comment]
After this add to library works like charm! creates folder and files but library auto scan not triggered. I need to manually library scan.. Maybe i broke something with this changes.

**Comment by i96751414** [comment]
Can you try with the following code please?
```
self._directory = xbmc.translatePath(get_library_path())
```

This way one can set it on settings (even if it's a special:// path, which seems to be the case).

**Comment by BTopbas** [comment]
> Can you try with the following code please?
> 
> ```
> self._directory = xbmc.translatePath(get_library_path())
> ```
> 
> This way one can set it on settings (even if it's a special:// path, which seems to be the case).

Works!!
xbmc.translatePath needs to "import xbmc" and also we have "from xbmc import executebuiltin, Monitor" this lines compatible each other? I don't have any error but library auto scan function look like not works..

Now i am looking logs for find something..

**Comment by BTopbas** [comment]
```
def update_shows(self, wait=False):
        LibraryMonitor().start_scan(self._shows_directory, wait)

def update_movies(self, wait=False):
        LibraryMonitor().start_scan(self._movies_directory, wait)
```
Why use the different monitors for shows and movies? I added "import json" in library.py and changed here to 

```
def update_shows(self, wait=False):
        jsonCommand = {'jsonrpc':'2.0','method':'VideoLibrary.Scan','id':10}
        xbmc.executeJSONRPC(json.dumps(jsonCommand))

    def update_movies(self, wait=False):
        jsonCommand = {'jsonrpc':'2.0','method':'VideoLibrary.Scan','id':10}
        xbmc.executeJSONRPC(json.dumps(jsonCommand))
```
And now library auto-scan successfully when adding an item to the library. I don't know this is Kodi Matrix or Apple TV problem but the solution is here. When adding a show or a movie, VideoLibrary.Scan triggered and scanned automatically.

Okey. this is a buggy. When adding one show its no problem scanning start but if you add another show when still scanning stops. So you need to wait to finish adding the first item to the library.

**Comment by i96751414** [comment]
Thank you for finding the paths issue!

"_Okey. this is a buggy. When adding one show its no problem scanning start but if you add another show when still scanning stops. So you need to wait to finish adding the first item to the library._" I believe this is kodi default behavior actually. If you start a new scan, the old scan will stop. It should not be a problem, as the new scan will find all the shows/movies.

The monitor is a custom implementation. Basically it allows to scan and block until the scan is finished. Also, it only scans a specific type of media (movies or shows). I would like to understand better why the current implementation is not working. I would say it is related with the provided path:
```
LibraryMonitor().start_scan(self._shows_directory, wait)
```

**Comment by BTopbas** [comment]
> Thank you for finding the paths issue!
> 
> "_Okey. this is a buggy. When adding one show its no problem scanning start but if you add another show when still scanning stops. So you need to wait to finish adding the first item to the library._" I believe this is kodi default behavior actually. If you start a new scan, the old scan will stop. It should not be a problem, as the new scan will find all the shows/movies.
> 
> The monitor is a custom implementation. Basically it allows to scan and block until the scan is finished. Also, it only scans a specific type of media (movies or shows). I would like to understand better why the current implementation is not working. I would say it is related with the provided path:
> 
> ```
> LibraryMonitor().start_scan(self._shows_directory, wait)
> ```

I think same. Something with path. I was looking logs but not found any error.

**Comment by i96751414** [comment]
Please do one thing:
Change https://github.com/i96751414/plugin.video.flix/blob/master/lib/service.py#L31 and https://github.com/i96751414/plugin.video.flix/blob/master/lib/navigation.py#L29 to
```
set_logger(level=logging.DEBUG)
```
Then activate DEBUG mode in Kodi and send me the logs please.

**Comment by BTopbas** [comment]
[kodi.log](https://github.com/i96751414/plugin.video.flix/files/4907532/kodi.log)

**Comment by BTopbas** [comment]
@i96751414 I sent a mail to you friend.

**Comment by i96751414** [comment]
I'm going to close this issue as the original problem was solved. If the library problem persists, please feel free to open a new issue for that, so we can track it. Cheers
