### ISSUE TITLE
Python 3 Fix for future Python 3 version

### ISSUE THREAD

**Issue by BTopbas** [i96751414/plugin.video.flix#4]
When trying to send the provider, Flix gives an error "TypeError: a bytes-like object is required, not 'str'"
To fix this: In lib/api/flix/provider.py
change this line(33):
`data_b64 = bytes_to_str(base64.b64encode(json.dumps(data)))`
to
`data_b64 = bytes_to_str(base64.b64encode(json.dumps(data).encode()))`

I think this is only needed python 3 and up.

**Comment by i96751414** [comment]
Thanks. I will check this later today.
