### ISSUE TITLE
Flix subtitle won't show all subtitles on OpenSubtitles

### ISSUE THREAD

**Issue by uomar8** [i96751414/plugin.video.flix#6]
![20210905_011110](https://user-images.githubusercontent.com/7046347/132109186-a5466d85-7fbf-440a-bc71-e82921b020f0.jpg)
![20210905_011137](https://user-images.githubusercontent.com/7046347/132109189-3654333d-018a-42f1-a6d0-32af830f861e.jpg)

That's why I thought it doesn't work my bad, it works but it gives less subtitles than OpenSubtitles addons

**Comment by i96751414** [comment]
Can you please enable debugging, run flix subtitles service and then provide the logs?

**Comment by uomar8** [comment]
[kodi.log](https://github.com/i96751414/plugin.video.flix/files/7131004/kodi.log)

**Comment by i96751414** [comment]
I believe this was improved with my last commit. Can you test it?

**Comment by uomar8** [comment]
> I believe this was improved with my last commit. Can you test it?

Yes now it's better than OpenSubtitles addons I got more subtitles
