### ISSUE TITLE
Can't startup if the skin is Estouchy

### ISSUE THREAD

**Issue by uomar8** [i96751414/plugin.video.flix#7]
Once I change the the skin to Estouchy (default for touch devices) it can't startup

Device info
Android version: 9
Kodi v20 (pre released)
Flix v0.0.14

Log:
[kodi.log](https://github.com/i96751414/plugin.video.flix/files/8821257/kodi.log)

**Comment by i96751414** [comment]
Did this only started happening with the new release?

**Comment by uomar8** [comment]
> Did this only started happening with the new release?

Only on the pre released I think it was a problem from kodi
I just install v20 Nightly version and it works fine

 log there are some warning I don't know if it's okay but it works 
[kodi.log](https://github.com/i96751414/plugin.video.flix/files/8822186/kodi.log)

V19 works perfectly too
