### ISSUE TITLE
Add brazilian portuguese

### ISSUE THREAD

**Issue by addon-rajada** [i96751414/plugin.video.flix#8]
Hi,

When Kodi in **Portuguese** everything is ok, but with language as **Portuguese (Brazil)** the content from API is returned in english. I think the problem is at ISO-639-1 dict, missing pt-BR entry. Could it be fixed?

**Comment by i96751414** [comment]
I wasn't able to reproduce your problem. Here everything seems to work fine.

Also make sure that under Settings > Player > Language you have "Preferred subtitle language" as Portuguese (Brazil).

**Comment by i96751414** [comment]
I'm closing this as there seems to be no problem. Feel free to reopen it otherwise.
