### ISSUE TITLE
[FIXED] Kodi 21 beta 3

### ISSUE THREAD

**Issue by icarok99** [i96751414/plugin.video.flix#9]
When I search for content it just keeps loading.

![Screenshot_2024-02-17-23-22-36-533_org xbmc kodi](https://github.com/i96751414/plugin.video.flix/assets/46580318/e85752f4-921d-48f6-9cf4-ede52abecbdf)

**Comment by i96751414** [comment]
There's indeed a problem here. I did some improvements to always make sure errors are well handled, still I believe there is a bug on Kodi side. It will require a bit more digging
